services:
  localstack:
    image: localstack/localstack:s3-latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - LOCALSTACK_HOST=localstack

  s3-bucket-exporter:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - localstack
    environment:
      - S3_ACCESS_KEY=test
      - S3_SECRET_KEY=test
      - S3_REGION=us-east-1
      - S3_ENDPOINT=http://localstack:4566
      - S3_FORCE_PATH_STYLE=true
      - SCRAPE_INTERVAL=3s
      - LOG_LEVEL=debug
    ports:
      - "9655:9655"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - localstack
      - s3-bucket-exporter
    environment:
      - S3_ACCESS_KEY=test
      - S3_SECRET_KEY=test
      - S3_REGION=us-east-1
      - S3_ENDPOINT=http://localstack:4566
      - S3_EXPORTER_URL=http://s3-bucket-exporter:9655/metrics
    volumes:
      - ./tests:/app/tests
